syms th1 th2 th3 real
forward = [cos(th1)+ cos(th1+th2)+ cos(th1+th2+th3); ...
            sin(th1)+ sin(th1+th2)+ sin(th1+th2+th3)]
jac = jacobian(forward, [th1,th2,th3])  
detJJT = det(jac*jac.')
d_detJJT = [...
simplify(diff(detJJT,th1));...
simplify(diff(detJJT,th2));...
simplify(diff(detJJT,th3))]
v_ellipse = simplify(jac*jac.')